---
# tasks file for nginx-role
- name: Install EPEL repo
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Install nginx packages
  become: true
  ansible.builtin.yum:
    name: nginx
- name: Deploy config
  become: true
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Nginx restart service
